import http from 'node:http';
import path from 'node:path';
import fs from 'node:fs';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { Pool } from 'pg';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const publicDir=path.join(__dirname,'public');
const PORT=Number(process.env.PORT||3000);
const TZ=process.env.TZ||'Asia/Aden';
const SESSION_SECRET=process.env.SESSION_SECRET||'CHANGE-ME-IN-PRODUCTION';
if(!process.env.DATABASE_URL){console.error('DATABASE_URL is required. Copy .env.example to your host environment.');process.exit(1)}
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL.includes('sslmode=require')||process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false,max:10,idleTimeoutMillis:30000,connectionTimeoutMillis:10000});
const permissions=[
 ['dashboard.view','لوحة التحكم'],['employees.view','عرض الموظفين'],['employees.manage','إدارة الموظفين'],['attendance.manage','إدارة الحضور'],['production.manage','إدارة الإنتاج'],['allowances.manage','إدارة الصرفة اليومية'],['withdrawals.manage','إدارة السحبيات'],['adjustments.manage','إدارة التسويات'],['ledger.view','عرض دفتر الحركات'],['ledger.post','ترحيل الحركات'],['periods.manage','إدارة الفترات والإقفال'],['reports.view','عرض التقارير'],['reports.export','تصدير التقارير'],['users.manage','إدارة المستخدمين'],['permissions.manage','إدارة الصلاحيات'],['audit.view','عرض سجل التدقيق'],['settings.manage','إدارة الإعدادات'],['backup.manage','النسخ الاحتياطي والاستعادة'],['attachments.manage','إدارة المرفقات']
];
const roles=['مدير','محاسب','مدخل بيانات','مستخدم قراءة'];
const roleDefaults={
 'مدير':permissions.map(x=>x[0]),
 'محاسب':permissions.map(x=>x[0]).filter(x=>!['users.manage','permissions.manage','backup.manage'].includes(x)),
 'مدخل بيانات':['dashboard.view','employees.view','employees.manage','attendance.manage','production.manage','allowances.manage','withdrawals.manage','adjustments.manage','ledger.view'],
 'مستخدم قراءة':['dashboard.view','employees.view','ledger.view','reports.view']
};
const now=()=>new Date().toISOString();
const localDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:TZ}).format(new Date());
const money=v=>{const n=Number(v);if(!Number.isFinite(n)||n<0)throw Error('المبلغ يجب أن يكون رقمًا غير سالب');return Math.round((n+Number.EPSILON)*100)/100};
const q=async(text,params=[])=>{const r=await pool.query(text,params);return r.rows};
const one=async(text,params=[])=>{const r=await pool.query(text,params);return r.rows[0]||null};
const exec=async(text,params=[])=>{const r=await pool.query(text,params);return r};
function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){return `${salt}:${crypto.scryptSync(password,salt,64).toString('hex')}`}
function verifyPassword(password,stored){if(!stored)return false;const [salt,key]=stored.split(':');if(!salt||!key)return false;const actual=crypto.scryptSync(password,salt,64);const expected=Buffer.from(key,'hex');return expected.length===actual.length&&crypto.timingSafeEqual(expected,actual)}
function sessionSign(id){return crypto.createHmac('sha256',SESSION_SECRET).update(String(id)).digest('hex')}
function setCookie(res,id){const token=`${id}.${sessionSign(id)}`;res.setHeader('Set-Cookie',`sid=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=28800${process.env.NODE_ENV==='production'?'; Secure':''}`)}
function sessionId(req){const token=(req.headers.cookie||'').match(/(?:^|; )sid=([^;]+)/)?.[1];if(!token)return null;const [id,sig]=token.split('.');if(!id||sig!==sessionSign(id))return null;return Number(id)}
async function requireAuth(req){const id=sessionId(req);if(!id)throw Object.assign(Error('يجب تسجيل الدخول'),{status:401});const u=await one('SELECT id,username,name,role,active FROM users WHERE id=$1',[id]);if(!u||!u.active)throw Object.assign(Error('المستخدم غير نشط'),{status:403});return u}
async function can(u,code){if(u.role==='مدير')return true;return !!await one('SELECT 1 FROM role_permissions rp JOIN roles r ON r.id=rp.role_id JOIN permissions p ON p.id=rp.permission_id WHERE r.name=$1 AND p.code=$2',[u.role,code])}
async function requirePerm(req,code){const u=await requireAuth(req);if(!await can(u,code))throw Object.assign(Error('ليس لديك صلاحية لتنفيذ هذه العملية'),{status:403});return u}
async function audit(userId,action,type,id,before=null,after=null,reason=null,ip=null){await exec('INSERT INTO audit_logs(user_id,action,entity_type,entity_id,before_json,after_json,reason,ip) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[userId||null,action,type,id==null?null:String(id),before?JSON.stringify(before):null,after?JSON.stringify(after):null,reason,ip])}
async function init(){
await exec(`CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,username TEXT UNIQUE NOT NULL,name TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'مدخل بيانات',password_hash TEXT NOT NULL,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS roles(id BIGSERIAL PRIMARY KEY,name TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS permissions(id BIGSERIAL PRIMARY KEY,code TEXT UNIQUE NOT NULL,name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS role_permissions(role_id BIGINT REFERENCES roles(id) ON DELETE CASCADE,permission_id BIGINT REFERENCES permissions(id) ON DELETE CASCADE,PRIMARY KEY(role_id,permission_id));
CREATE TABLE IF NOT EXISTS employees(id BIGSERIAL PRIMARY KEY,code TEXT UNIQUE NOT NULL,name TEXT NOT NULL,phone TEXT,address TEXT,type TEXT NOT NULL CHECK(type IN ('راتب شهري','إنتاج بالقطعة')),monthly_salary NUMERIC(14,2) NOT NULL DEFAULT 0,daily_allowance_limit NUMERIC(14,2) NOT NULL DEFAULT 0,work_hours NUMERIC(8,2) NOT NULL DEFAULT 12,work_days_per_week INTEGER NOT NULL DEFAULT 6,payment_method TEXT DEFAULT 'نقدًا',start_date DATE,end_date DATE,status TEXT NOT NULL DEFAULT 'نشط',notes TEXT,created_by BIGINT,updated_by BIGINT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS employee_history(id BIGSERIAL PRIMARY KEY,employee_id BIGINT NOT NULL REFERENCES employees(id),effective_date DATE NOT NULL,field_name TEXT NOT NULL,old_value TEXT,new_value TEXT,reason TEXT,user_id BIGINT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS periods(id BIGSERIAL PRIMARY KEY,month INTEGER NOT NULL,year INTEGER NOT NULL,start_date DATE NOT NULL,end_date DATE NOT NULL,status TEXT NOT NULL DEFAULT 'مفتوحة',closed_at TIMESTAMPTZ,closed_by BIGINT,reopen_reason TEXT,UNIQUE(month,year));
CREATE TABLE IF NOT EXISTS opening_balances(id BIGSERIAL PRIMARY KEY,employee_id BIGINT NOT NULL REFERENCES employees(id),period_id BIGINT NOT NULL REFERENCES periods(id),amount NUMERIC(14,2) NOT NULL,source TEXT NOT NULL DEFAULT 'افتتاحي',created_by BIGINT,UNIQUE(employee_id,period_id));
CREATE TABLE IF NOT EXISTS ledger(id BIGSERIAL PRIMARY KEY,employee_id BIGINT NOT NULL REFERENCES employees(id),transaction_date DATE NOT NULL,posting_date DATE NOT NULL,period_id BIGINT NOT NULL REFERENCES periods(id),transaction_type TEXT NOT NULL,description TEXT NOT NULL,debit NUMERIC(14,2) NOT NULL DEFAULT 0,credit NUMERIC(14,2) NOT NULL DEFAULT 0,amount NUMERIC(14,2) NOT NULL,reference_type TEXT,reference_id TEXT,created_by BIGINT,status TEXT NOT NULL DEFAULT 'مرحلة',notes TEXT,idempotency_key TEXT UNIQUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ,CHECK(debit>=0 AND credit>=0),CHECK(NOT(debit>0 AND credit>0)));
CREATE INDEX IF NOT EXISTS idx_ledger_emp_date ON ledger(employee_id,transaction_date,id);
CREATE TABLE IF NOT EXISTS attendance(id BIGSERIAL PRIMARY KEY,employee_id BIGINT NOT NULL REFERENCES employees(id),work_date DATE NOT NULL,status TEXT NOT NULL DEFAULT 'حاضر',absent_hours NUMERIC(8,2) NOT NULL DEFAULT 0,deduction_amount NUMERIC(14,2) NOT NULL DEFAULT 0,reason TEXT,created_by BIGINT,updated_by BIGINT,UNIQUE(employee_id,work_date));
CREATE TABLE IF NOT EXISTS production_items(id BIGSERIAL PRIMARY KEY,code TEXT UNIQUE NOT NULL,name TEXT NOT NULL,description TEXT,unit TEXT DEFAULT 'قطعة',default_price NUMERIC(14,2) NOT NULL DEFAULT 0,active BOOLEAN NOT NULL DEFAULT TRUE,price_start_date DATE,price_end_date DATE);
CREATE TABLE IF NOT EXISTS production_logs(id BIGSERIAL PRIMARY KEY,employee_id BIGINT NOT NULL REFERENCES employees(id),item_id BIGINT REFERENCES production_items(id),work_date DATE NOT NULL,item_name TEXT NOT NULL,quantity NUMERIC(14,3) NOT NULL CHECK(quantity>0),price_per_unit NUMERIC(14,2) NOT NULL CHECK(price_per_unit>=0),total_price NUMERIC(14,2) NOT NULL,is_invoiced BOOLEAN NOT NULL DEFAULT FALSE,invoice_id BIGINT,work_order_ref TEXT,status TEXT NOT NULL DEFAULT 'مسجلة',created_by BIGINT,notes TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS production_invoices(id BIGSERIAL PRIMARY KEY,invoice_no TEXT UNIQUE NOT NULL,employee_id BIGINT NOT NULL REFERENCES employees(id),from_date DATE NOT NULL,to_date DATE NOT NULL,total NUMERIC(14,2) NOT NULL,discount NUMERIC(14,2) NOT NULL DEFAULT 0,net_total NUMERIC(14,2) NOT NULL,status TEXT NOT NULL DEFAULT 'مسودة',created_by BIGINT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),approved_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS daily_allowances(id BIGSERIAL PRIMARY KEY,employee_id BIGINT NOT NULL REFERENCES employees(id),allowance_date DATE NOT NULL,limit_amount NUMERIC(14,2) NOT NULL,earned_amount NUMERIC(14,2) NOT NULL,paid_amount NUMERIC(14,2) NOT NULL DEFAULT 0,recovered_amount NUMERIC(14,2) NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'مستحقة',recovery_reason TEXT,recovered_at TIMESTAMPTZ,created_by BIGINT,UNIQUE(employee_id,allowance_date));
CREATE TABLE IF NOT EXISTS withdrawals(id BIGSERIAL PRIMARY KEY,employee_id BIGINT NOT NULL REFERENCES employees(id),withdrawal_date DATE NOT NULL,amount NUMERIC(14,2) NOT NULL CHECK(amount>0),payment_method TEXT NOT NULL,purpose TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'معتمدة',notes TEXT,created_by BIGINT,approved_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS adjustments(id BIGSERIAL PRIMARY KEY,employee_id BIGINT NOT NULL REFERENCES employees(id),adjustment_date DATE NOT NULL,type TEXT NOT NULL CHECK(type IN ('مكافأة','خصم','تسوية','سلفة')),amount NUMERIC(14,2) NOT NULL CHECK(amount>0),reason TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'معتمدة',created_by BIGINT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT);
CREATE TABLE IF NOT EXISTS audit_logs(id BIGSERIAL PRIMARY KEY,user_id BIGINT,action TEXT NOT NULL,entity_type TEXT,entity_id TEXT,before_json JSONB,after_json JSONB,reason TEXT,ip INET,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS jobs(id BIGSERIAL PRIMARY KEY,job_key TEXT UNIQUE NOT NULL,job_date DATE NOT NULL,status TEXT NOT NULL,result JSONB,error TEXT,started_at TIMESTAMPTZ,finished_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS attachments(id BIGSERIAL PRIMARY KEY,entity_type TEXT NOT NULL,entity_id BIGINT NOT NULL,file_name TEXT NOT NULL,mime_type TEXT,size_bytes BIGINT NOT NULL,data BYTEA NOT NULL,sha256 TEXT NOT NULL,uploaded_by BIGINT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS backup_records(id BIGSERIAL PRIMARY KEY,name TEXT UNIQUE NOT NULL,data JSONB NOT NULL,created_by BIGINT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());`);
for(const [code,name] of permissions)await exec('INSERT INTO permissions(code,name) VALUES($1,$2) ON CONFLICT(code) DO UPDATE SET name=EXCLUDED.name',[code,name]);
for(const name of roles)await exec('INSERT INTO roles(name) VALUES($1) ON CONFLICT(name) DO NOTHING',[name]);
for(const role of roles){const r=await one('SELECT id FROM roles WHERE name=$1',[role]);for(const code of roleDefaults[role]){const p=await one('SELECT id FROM permissions WHERE code=$1',[code]);await exec('INSERT INTO role_permissions(role_id,permission_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[r.id,p.id])}}
const settings={shop_name:'مشغل العلاء',timezone:TZ,work_hours:'12',week_start:'الأحد',currency:'YER',decimal_places:'2',rounding:'HALF_UP',auto_daily_salary:'1',auto_daily_allowance:'1'};for(const [k,v] of Object.entries(settings))await exec('INSERT INTO settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO NOTHING',[k,v]);
const admin=await one('SELECT id FROM users WHERE username=$1',['admin']);if(!admin)await exec('INSERT INTO users(username,name,role,password_hash) VALUES($1,$2,$3,$4)',['admin','المدير','مدير',hashPassword('admin123')]);
await ensurePeriod(localDate());
}
async function ensurePeriod(date){const [y,m]=String(date).slice(0,7).split('-').map(Number);const first=`${y}-${String(m).padStart(2,'0')}-01`;const last=new Date(Date.UTC(y,m,0)).toISOString().slice(0,10);const r=await one('INSERT INTO periods(month,year,start_date,end_date) VALUES($1,$2,$3,$4) ON CONFLICT(month,year) DO UPDATE SET month=EXCLUDED.month RETURNING *',[m,y,first,last]);return r}
async function assertOpen(date){const p=await ensurePeriod(date);if(p.status!=='مفتوحة')throw Error('الفترة مغلقة ولا يمكن إضافة حركة إليها');return p}
async function postLedger({employee_id,date,type,desc,amount,direction,refType,refId,notes,key,userId}){amount=money(amount);const p=await assertOpen(date);if(key){const ex=await one('SELECT * FROM ledger WHERE idempotency_key=$1',[key]);if(ex)return ex}const debit=direction==='debit'?amount:0,credit=direction==='credit'?amount:0;const r=await one('INSERT INTO ledger(employee_id,transaction_date,posting_date,period_id,transaction_type,description,debit,credit,amount,reference_type,reference_id,created_by,status,notes,idempotency_key) VALUES($1,$2,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,\'مرحلة\',$12,$13) ON CONFLICT(idempotency_key) DO NOTHING RETURNING *',[employee_id,date,p.id,type,desc,debit,credit,amount,refType||null,refId?String(refId):null,userId,notes||null,key||null]);const row=r||await one('SELECT * FROM ledger WHERE idempotency_key=$1',[key]);await audit(userId,'POST','ledger',row.id,null,row);return row}
async function balance(employee,until=null){const args=[employee];let where='';if(until){args.push(until);where=' AND transaction_date <= $2'}const a=await one(`SELECT COALESCE(SUM(credit-debit),0) b FROM ledger WHERE employee_id=$1 AND status IN ('مرحلة','معتمدة')${where}`,args);return Number(a.b||0)}
function json(res,status,data){const b=Buffer.from(JSON.stringify(data));res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Content-Length':b.length,'Cache-Control':'no-store'});res.end(b)}
async function body(req){let s='';for await(const c of req)s+=c;if(s.length>20*1024*1024)throw Error('الطلب كبير جدًا');return s?JSON.parse(s):{}}
function sendHtml(res,s){const b=Buffer.from(s);res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Content-Length':b.length});res.end(b)}
function csv(rows){if(!rows.length)return '\ufeff';const keys=Object.keys(rows[0]);return '\ufeff'+keys.join(',')+'\n'+rows.map(r=>keys.map(k=>`"${String(r[k]??'').replaceAll('"','""')}"`).join(',')).join('\n')}
function htmlReport(title,content){return `<!doctype html><html dir="rtl"><head><meta charset="utf-8"><title>${title}</title><style>body{font-family:Arial;direction:rtl;padding:30px;color:#111}table{width:100%;border-collapse:collapse}th,td{border:1px solid #bbb;padding:7px}button{padding:8px 15px}@media print{button{display:none}}</style></head><body><button onclick="print()">طباعة / حفظ PDF</button><h1>مشغل العلاء</h1><h2>${title}</h2>${content}</body></html>`}
function datePlus(date,days){const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
function dateDiffDays(from,to){const a=new Date(`${from}T12:00:00Z`),b=new Date(`${to}T12:00:00Z`);return Math.floor((b-a)/86400000)}
function employeeEligibleOn(e,date){return e.type==='راتب شهري' && e.start_date && date>=String(e.start_date).slice(0,10) && (!e.end_date || date<=String(e.end_date).slice(0,10))}
async function accrueEmployeeDay(e,date,userId){if(!employeeEligibleOn(e,date))return {salary:false,allowance:false,paidAllowance:false};let salary=false,allowance=false,paidAllowance=false;const amount=money(Number(e.monthly_salary)/30);if(amount>0){const row=await postLedger({employee_id:e.id,date,type:'استحقاق راتب يومي',desc:`استحقاق راتب يومي ${date}`,amount,direction:'credit',refType:'daily_salary',refId:e.id,key:`salary:${e.id}:${date}`,userId});salary=!!row}const a=await one('INSERT INTO daily_allowances(employee_id,allowance_date,limit_amount,earned_amount,created_by) VALUES($1,$2,$3,$3,$4) ON CONFLICT(employee_id,allowance_date) DO UPDATE SET limit_amount=EXCLUDED.limit_amount,earned_amount=EXCLUDED.earned_amount WHERE daily_allowances.paid_amount=0 AND daily_allowances.recovered_amount=0 RETURNING *',[e.id,date,money(e.daily_allowance_limit||0),userId]);if(a&&Number(a.earned_amount)>0){await postLedger({employee_id:e.id,date,type:'صرفة يومية',desc:`استحقاق صرفة يومية ${date}`,amount:a.earned_amount,direction:'credit',refType:'daily_allowance',refId:a.id,key:`allowance:${e.id}:${date}`,userId});allowance=true;if(Number(a.paid_amount)===0){const paid=await one("UPDATE daily_allowances SET paid_amount=earned_amount,status='مدفوعة' WHERE id=$1 AND paid_amount=0 AND recovered_amount=0 RETURNING *",[a.id]);if(paid){await postLedger({employee_id:e.id,date,type:'صرف صرفة يومية',desc:`صرف الصرفة اليومية ${date}`,amount:paid.earned_amount,direction:'debit',refType:'allowance_payment',refId:paid.id,key:`allowance-payment:${paid.id}`,userId});paidAllowance=true}}}return {salary,allowance,paidAllowance}}
async function runDaily(date,userId){const key=`daily:${date}`;const existing=await one('SELECT * FROM jobs WHERE job_key=$1',[key]);if(existing?.status==='success')return existing.result;const job=await one("INSERT INTO jobs(job_key,job_date,status,started_at) VALUES($1,$2,$3,NOW()) ON CONFLICT(job_key) DO UPDATE SET status='running',started_at=NOW() RETURNING *",[key,date,'running']);let salary=0,allowance=0;try{const employees=await q("SELECT * FROM employees WHERE status='نشط' AND type='راتب شهري' AND start_date IS NOT NULL AND start_date <= $1 AND (end_date IS NULL OR end_date >= $1)",[date]);for(const e of employees){const r=await accrueEmployeeDay(e,date,userId);if(r.salary)salary++;if(r.allowance)allowance++}const result={jobKey:key,salary,allowance,status:'success',date};await exec("UPDATE jobs SET status='success',result=$1,finished_at=NOW() WHERE id=$2",[result,job.id]);await audit(userId,'RUN','job',job.id,null,result);return result}catch(e){await exec("UPDATE jobs SET status='failed',error=$1,finished_at=NOW() WHERE id=$2",[e.message,job.id]);throw e}}
async function catchUpDaily(userId=null){const today=localDate();const rows=await q("SELECT * FROM employees WHERE status='نشط' AND type='راتب شهري' AND start_date IS NOT NULL AND start_date <= $1 AND (end_date IS NULL OR end_date >= $1)",[today]);const result={employees:rows.length,days:0,salary:0,allowance:0,paidAllowance:0,errors:[]};for(const e of rows){const start=String(e.start_date).slice(0,10);const end=e.end_date&&String(e.end_date).slice(0,10)<today?String(e.end_date).slice(0,10):today;const days=Math.max(0,dateDiffDays(start,end));for(let i=0;i<=days;i++){const date=datePlus(start,i);try{const r=await accrueEmployeeDay(e,date,userId);result.days++;if(r.salary)result.salary++;if(r.allowance)result.allowance++;if(r.paidAllowance)result.paidAllowance++}catch(err){result.errors.push({employee_id:e.id,date,error:err.message});console.error(`Daily accrual skipped for employee ${e.id} on ${date}:`,err.message)}}}return result}
function scheduleDaily(){const check=async()=>{const localTime=new Intl.DateTimeFormat('en-GB',{timeZone:TZ,hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date());if(localTime==='23:59'){try{await runDaily(localDate(),null)}catch(e){console.error('Automatic daily payroll failed:',e.message)}}};setInterval(check,60000);check().catch(()=>{})}
async function handler(req,res){try{const u=new URL(req.url,`http://${req.headers.host}`),p=u.pathname,method=req.method;if(method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type'});return res.end()}
if(p==='/api/health')return json(res,200,{ok:true,time:now(),db:'postgresql',version:'4.0.0'});
if(p==='/api/login'&&method==='POST'){const b=await body(req),x=await one('SELECT * FROM users WHERE username=$1',[b.username]);if(!x||!x.active||!verifyPassword(b.password||'',x.password_hash))throw Object.assign(Error('اسم المستخدم أو كلمة المرور غير صحيحة'),{status:401});setCookie(res,x.id);return json(res,200,{user:{id:x.id,username:x.username,name:x.name,role:x.role,active:x.active}})}
if(p==='/api/logout'&&method==='POST'){res.setHeader('Set-Cookie','sid=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0');return json(res,200,{ok:true})}
if(p==='/api/me'){const user=await requireAuth(req);const ps=await q('SELECT p.code FROM role_permissions rp JOIN roles r ON r.id=rp.role_id JOIN permissions p ON p.id=rp.permission_id WHERE r.name=$1',[user.role]);return json(res,200,{user,permissions:ps.map(x=>x.code)})}
if(p==='/api/dashboard'){const user=await requirePerm(req,'dashboard.view');const em=await q("SELECT e.*,COALESCE((SELECT SUM(l.credit-l.debit) FROM ledger l WHERE l.employee_id=e.id AND l.status IN ('مرحلة','معتمدة')),0) balance FROM employees e ORDER BY e.id");const metrics=await one("SELECT COALESCE(SUM(credit),0) credits,COALESCE(SUM(debit),0) debits,COUNT(*) movements FROM ledger WHERE status IN ('مرحلة','معتمدة')");return json(res,200,{user,employees:em,metrics:{...metrics,balance:Number(metrics.credits)-Number(metrics.debits)},period:await one('SELECT * FROM periods ORDER BY year DESC,month DESC LIMIT 1'),pending:{attendance:Number((await one("SELECT COUNT(*) c FROM attendance WHERE status='مسجلة'"))?.c||0),production:Number((await one('SELECT COUNT(*) c FROM production_logs WHERE is_invoiced=false'))?.c||0),withdrawals:Number((await one("SELECT COUNT(*) c FROM withdrawals WHERE status='معلقة'"))?.c||0)}})}
if(p==='/api/employees'&&method==='GET'){await requirePerm(req,'employees.view');return json(res,200,await q("SELECT e.*,COALESCE((SELECT SUM(credit-debit) FROM ledger l WHERE l.employee_id=e.id AND l.status IN ('مرحلة','معتمدة')),0) balance FROM employees e ORDER BY e.id DESC"))}
if(p==='/api/employees'&&method==='POST'){const user=await requirePerm(req,'employees.manage'),b=await body(req);if(!b.name)throw Error('اسم الموظف مطلوب');const startDate=b.start_date||localDate();if(startDate>localDate())throw Error('تاريخ بداية العمل لا يمكن أن يكون في المستقبل');const r=await one('INSERT INTO employees(code,name,phone,address,type,monthly_salary,daily_allowance_limit,work_hours,work_days_per_week,payment_method,start_date,status,notes,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$14) RETURNING *',[b.code||`EMP-${Date.now()}`,b.name,b.phone||null,b.address||null,b.type||'راتب شهري',money(b.monthly_salary||0),money(b.daily_allowance_limit||0),Number(b.work_hours||12),Number(b.work_days_per_week||6),b.payment_method||'نقدًا',startDate,b.status||'نشط',b.notes||null,user.id]);if(r.status==='نشط'&&r.type==='راتب شهري'){const days=Math.max(0,dateDiffDays(String(r.start_date).slice(0,10),localDate()));for(let i=0;i<=days;i++)await accrueEmployeeDay(r,datePlus(String(r.start_date).slice(0,10),i),user.id)}await audit(user.id,'CREATE','employee',r.id,null,r);return json(res,201,r)}
if(p.match(/^\/api\/employees\/\d+$/)&&method==='GET'){await requirePerm(req,'employees.view');const id=Number(p.split('/').pop()),e=await one('SELECT * FROM employees WHERE id=$1',[id]);if(!e)throw Error('الموظف غير موجود');return json(res,200,{employee:e,balance:await balance(id),ledger:await q('SELECT * FROM ledger WHERE employee_id=$1 ORDER BY transaction_date DESC,id DESC',[id]),attachments:await q('SELECT id,file_name,mime_type,size_bytes,sha256,created_at FROM attachments WHERE entity_type=$1 AND entity_id=$2 ORDER BY id DESC',['employee',id])})}
if(p.match(/^\/api\/employees\/\d+$/)&&method==='PUT'){const user=await requirePerm(req,'employees.manage'),id=Number(p.split('/').pop()),b=await body(req),before=await one('SELECT * FROM employees WHERE id=$1',[id]);if(!before)throw Error('الموظف غير موجود');if(b.start_date && b.start_date>localDate())throw Error('تاريخ بداية العمل لا يمكن أن يكون في المستقبل');const fields=['code','name','phone','address','type','monthly_salary','daily_allowance_limit','work_hours','work_days_per_week','payment_method','start_date','end_date','status','notes'];const vals=[b.code??before.code,b.name??before.name,b.phone??before.phone,b.address??before.address,b.type??before.type,money(b.monthly_salary??before.monthly_salary),money(b.daily_allowance_limit??before.daily_allowance_limit),Number(b.work_hours??before.work_hours),Number(b.work_days_per_week??before.work_days_per_week),b.payment_method??before.payment_method,b.start_date??before.start_date,b.end_date??before.end_date,b.status??before.status,b.notes??before.notes];const r=await one('UPDATE employees SET code=$1,name=$2,phone=$3,address=$4,type=$5,monthly_salary=$6,daily_allowance_limit=$7,work_hours=$8,work_days_per_week=$9,payment_method=$10,start_date=$11,end_date=$12,status=$13,notes=$14,updated_by=$15,updated_at=NOW() WHERE id=$16 RETURNING *',[...vals,user.id,id]);for(const f of fields){const ov=before[f],nv=r[f];if(String(ov??'')!==String(nv??''))await exec('INSERT INTO employee_history(employee_id,effective_date,field_name,old_value,new_value,reason,user_id) VALUES($1,$2,$3,$4,$5,$6,$7)',[id,localDate(),f,String(ov??''),String(nv??''),'تعديل بيانات الموظف',user.id])}if(r.status==='نشط'&&r.type==='راتب شهري'&&r.start_date){const start=String(r.start_date).slice(0,10),today=localDate(),days=Math.max(0,dateDiffDays(start,today));for(let i=0;i<=days;i++){try{await accrueEmployeeDay(r,datePlus(start,i),user.id)}catch(err){console.error('Employee update accrual skipped:',err.message)}}}await audit(user.id,'UPDATE','employee',id,before,r);return json(res,200,r)}
if(p.match(/^\/api\/employees\/\d+$/)&&method==='DELETE'){const user=await requirePerm(req,'employees.manage'),id=Number(p.split('/').pop()),before=await one('SELECT * FROM employees WHERE id=$1',[id]);if(!before)throw Error('الموظف غير موجود');const linked=await one('SELECT (SELECT COUNT(*) FROM ledger WHERE employee_id=$1) ledger_count,(SELECT COUNT(*) FROM attendance WHERE employee_id=$1) attendance_count,(SELECT COUNT(*) FROM daily_allowances WHERE employee_id=$1) allowance_count,(SELECT COUNT(*) FROM withdrawals WHERE employee_id=$1) withdrawal_count,(SELECT COUNT(*) FROM adjustments WHERE employee_id=$1) adjustment_count,(SELECT COUNT(*) FROM production_logs WHERE employee_id=$1) production_count',[id]);const total=Object.values(linked).reduce((a,v)=>a+Number(v||0),0);if(total>0)throw Error('لا يمكن حذف الموظف لأنه مرتبط بسجلات مالية أو تشغيلية. استخدم تعديل الحالة إلى غير نشط بدلًا من الحذف.');await exec('DELETE FROM employee_history WHERE employee_id=$1',[id]);await exec('DELETE FROM employees WHERE id=$1',[id]);await audit(user.id,'DELETE','employee',id,before,null,'حذف موظف بلا سجلات مرتبطة');return json(res,200,{ok:true,id})}

if(p==='/api/ledger'&&method==='GET'){await requirePerm(req,'ledger.view');return json(res,200,await q('SELECT l.*,e.name employee_name,e.code FROM ledger l JOIN employees e ON e.id=l.employee_id ORDER BY l.transaction_date DESC,l.id DESC'))}
if(p==='/api/ledger'&&method==='POST'){const user=await requirePerm(req,'ledger.post'),b=await body(req);return json(res,201,await postLedger({employee_id:Number(b.employee_id),date:b.transaction_date||localDate(),type:b.transaction_type||'تعديل محاسبي',desc:b.description||'حركة',amount:b.amount,direction:b.direction||'credit',refType:b.reference_type,refId:b.reference_id,notes:b.notes,key:b.idempotency_key||`manual:${crypto.randomUUID()}`,userId:user.id}))}
if(p.match(/^\/api\/ledger\/\d+\/approve$/)&&method==='POST'){const user=await requirePerm(req,'ledger.post'),id=Number(p.split('/')[3]),before=await one('SELECT * FROM ledger WHERE id=$1',[id]);if(!before)throw Error('الحركة غير موجودة');await exec("UPDATE ledger SET status='معتمدة',updated_at=NOW() WHERE id=$1 AND status<>'ملغاة'",[id]);const after=await one('SELECT * FROM ledger WHERE id=$1',[id]);await audit(user.id,'APPROVE','ledger',id,before,after);return json(res,200,after)}
if(p==='/api/attendance'&&method==='GET'){await requirePerm(req,'attendance.manage');return json(res,200,await q('SELECT a.*,e.name employee_name FROM attendance a JOIN employees e ON e.id=a.employee_id ORDER BY work_date DESC'))}
if(p==='/api/attendance'&&method==='POST'){const user=await requirePerm(req,'attendance.manage'),b=await body(req),e=await one('SELECT * FROM employees WHERE id=$1',[b.employee_id]);if(!e)throw Error('الموظف غير موجود');const hours=Number(b.absent_hours||0);if(hours>Number(e.work_hours))throw Error('ساعات الغياب أكبر من ساعات العمل');const ded=money((Number(e.monthly_salary)/30/Number(e.work_hours))*hours);const existingAttendance=await one('SELECT id FROM attendance WHERE employee_id=$1 AND work_date=$2',[b.employee_id,b.work_date||localDate()]);if(existingAttendance)throw Error('تم تسجيل حضور/غياب هذا الموظف لهذا اليوم مسبقًا ولا يجوز استبداله بعد إنشاء القيد');const r=await one('INSERT INTO attendance(employee_id,work_date,status,absent_hours,deduction_amount,reason,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$7) RETURNING *',[b.employee_id,b.work_date||localDate(),b.status||'غائب',hours,ded,b.reason||null,user.id]);if(ded>0)await postLedger({employee_id:e.id,date:r.work_date,type:'خصم غياب',desc:`خصم غياب ${hours} ساعة`,amount:ded,direction:'debit',refType:'attendance',refId:r.id,key:`attendance:${r.id}`,userId:user.id});await audit(user.id,'UPSERT','attendance',r.id,null,r);return json(res,201,r)}
if(p==='/api/production/items'&&method==='GET'){await requirePerm(req,'production.manage');return json(res,200,await q('SELECT * FROM production_items ORDER BY id DESC'))}
if(p==='/api/production/items'&&method==='POST'){const user=await requirePerm(req,'production.manage'),b=await body(req),r=await one('INSERT INTO production_items(code,name,description,unit,default_price,price_start_date) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[b.code||`IT-${Date.now()}`,b.name,b.description||null,b.unit||'قطعة',money(b.default_price||0),b.price_start_date||localDate()]);await audit(user.id,'CREATE','production_item',r.id,null,r);return json(res,201,r)}
if(p==='/api/production'&&method==='GET'){await requirePerm(req,'production.manage');return json(res,200,await q('SELECT p.*,e.name employee_name,COALESCE(i.name,p.item_name) item FROM production_logs p JOIN employees e ON e.id=p.employee_id LEFT JOIN production_items i ON i.id=p.item_id ORDER BY work_date DESC,p.id DESC'))}
if(p==='/api/production'&&method==='POST'){const user=await requirePerm(req,'production.manage'),b=await body(req),item=b.item_id?await one('SELECT * FROM production_items WHERE id=$1',[b.item_id]):null,qty=Number(b.quantity||0),price=money(b.price_per_unit??item?.default_price??0);if(qty<=0)throw Error('الكمية يجب أن تكون أكبر من صفر');const r=await one('INSERT INTO production_logs(employee_id,item_id,work_date,item_name,quantity,price_per_unit,total_price,work_order_ref,created_by,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *',[b.employee_id,b.item_id||null,b.work_date||localDate(),item?.name||b.item_name,qty,price,money(qty*price),b.work_order_ref||null,user.id,b.notes||null]);await audit(user.id,'CREATE','production',r.id,null,r);return json(res,201,r)}
if(p==='/api/production/invoice'&&method==='POST'){const user=await requirePerm(req,'production.manage'),b=await body(req),client=await pool.connect();try{await client.query('BEGIN');const rows=(await client.query("SELECT * FROM production_logs WHERE employee_id=$1 AND work_date BETWEEN $2 AND $3 AND is_invoiced=false AND status='مسجلة' FOR UPDATE",[b.employee_id,b.from_date,b.to_date])).rows;if(!rows.length)throw Error('لا يوجد إنتاج غير مفوتر في الفترة');const total=money(rows.reduce((a,x)=>a+Number(x.total_price),0)),disc=money(b.discount||0);if(disc>total)throw Error('الخصم أكبر من الإجمالي');const r=(await client.query('INSERT INTO production_invoices(invoice_no,employee_id,from_date,to_date,total,discount,net_total,status,created_by,approved_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,NOW()) RETURNING *',[`INV-${Date.now()}`,b.employee_id,b.from_date,b.to_date,total,disc,total-disc,'معتمدة',user.id])).rows[0];for(const x of rows)await client.query('UPDATE production_logs SET is_invoiced=true,invoice_id=$1 WHERE id=$2',[r.id,x.id]);await client.query('COMMIT');await postLedger({employee_id:r.employee_id,date:r.to_date,type:'فاتورة إنتاج',desc:`فاتورة إنتاج ${r.invoice_no}`,amount:r.net_total,direction:'credit',refType:'production_invoice',refId:r.id,key:`invoice:${r.id}`,userId:user.id});await audit(user.id,'CREATE','production_invoice',r.id,null,r);return json(res,201,r)}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
if(p==='/api/production/invoices'&&method==='GET'){await requirePerm(req,'production.manage');return json(res,200,await q('SELECT i.*,e.name employee_name FROM production_invoices i JOIN employees e ON e.id=i.employee_id ORDER BY i.id DESC'))}
if(p==='/api/allowances'&&method==='GET'){const user=await requirePerm(req,'allowances.manage');await catchUpDaily(user.id);return json(res,200,await q("SELECT a.*,e.name employee_name,e.code employee_code,e.status employee_status FROM daily_allowances a JOIN employees e ON e.id=a.employee_id WHERE e.type='راتب شهري' ORDER BY allowance_date DESC,a.id DESC"))}
if(p==='/api/allowances/run'&&method==='POST'){const user=await requirePerm(req,'allowances.manage'),b=await body(req);return json(res,200,await runDaily(b.date||localDate(),user.id))}
if(p.match(/^\/api\/allowances\/\d+\/pay$/)&&method==='POST'){const user=await requirePerm(req,'allowances.manage'),id=Number(p.split('/')[3]),a=await one('SELECT * FROM daily_allowances WHERE id=$1',[id]);if(!a)throw Error('الصرفة غير موجودة');if(Number(a.paid_amount)>0)throw Error('تم تسجيل الصرف مسبقًا');const r=await one("UPDATE daily_allowances SET paid_amount=earned_amount,status='مدفوعة' WHERE id=$1 RETURNING *",[id]);await postLedger({employee_id:a.employee_id,date:a.allowance_date,type:'صرف صرفة يومية',desc:'صرف الصرفة اليومية',amount:a.earned_amount,direction:'debit',refType:'allowance_payment',refId:id,key:`allowance-payment:${id}`,userId:user.id});await audit(user.id,'PAY','allowance',id,a,r);return json(res,200,r)}
if(p.match(/^\/api\/allowances\/\d+\/recover$/)&&method==='POST'){const user=await requirePerm(req,'allowances.manage'),id=Number(p.split('/')[3]),b=await body(req),a=await one('SELECT * FROM daily_allowances WHERE id=$1',[id]);if(!a)throw Error('الصرفة غير موجودة');if(Number(a.recovered_amount)>0)throw Error('تم الاسترجاع مسبقًا');const r=await one("UPDATE daily_allowances SET recovered_amount=earned_amount,status='مسترجعة',recovery_reason=$1,recovered_at=NOW() WHERE id=$2 RETURNING *",[b.reason||'استرجاع',id]);await postLedger({employee_id:a.employee_id,date:a.allowance_date,type:'استرجاع صرفة',desc:r.recovery_reason,amount:a.earned_amount,direction:'debit',refType:'allowance_recovery',refId:id,key:`allowance-recovery:${id}`,userId:user.id});await audit(user.id,'RECOVER','allowance',id,a,r,b.reason);return json(res,200,r)}
if(p==='/api/withdrawals'&&method==='GET'){await requirePerm(req,'withdrawals.manage');return json(res,200,await q('SELECT w.*,e.name employee_name FROM withdrawals w JOIN employees e ON e.id=w.employee_id ORDER BY withdrawal_date DESC'))}
if(p==='/api/withdrawals'&&method==='POST'){const user=await requirePerm(req,'withdrawals.manage'),b=await body(req);if(!b.payment_method||!b.purpose)throw Error('طريقة الدفع والغرض إلزاميان');const r=await one('INSERT INTO withdrawals(employee_id,withdrawal_date,amount,payment_method,purpose,status,notes,created_by,approved_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,NOW()) RETURNING *',[b.employee_id,b.withdrawal_date||localDate(),money(b.amount),b.payment_method,b.purpose,'معتمدة',b.notes||null,user.id]);await postLedger({employee_id:r.employee_id,date:r.withdrawal_date,type:'سحب/دفعة',desc:r.purpose,amount:r.amount,direction:'debit',refType:'withdrawal',refId:r.id,key:`withdrawal:${r.id}`,userId:user.id});await audit(user.id,'CREATE','withdrawal',r.id,null,r);return json(res,201,r)}
if(p==='/api/adjustments'&&method==='GET'){await requirePerm(req,'adjustments.manage');return json(res,200,await q('SELECT a.*,e.name employee_name FROM adjustments a JOIN employees e ON e.id=a.employee_id ORDER BY id DESC'))}
if(p==='/api/adjustments'&&method==='POST'){const user=await requirePerm(req,'adjustments.manage'),b=await body(req);if(!b.reason)throw Error('سبب الحركة إلزامي');const r=await one('INSERT INTO adjustments(employee_id,adjustment_date,type,amount,reason,status,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[b.employee_id,b.date||localDate(),b.type,money(b.amount),b.reason,'معتمدة',user.id]);const credit=['مكافأة','تسوية'].includes(b.type);await postLedger({employee_id:r.employee_id,date:r.adjustment_date,type:r.type,desc:r.reason,amount:r.amount,direction:credit?'credit':'debit',refType:'adjustment',refId:r.id,key:`adjustment:${r.id}`,userId:user.id});await audit(user.id,'CREATE','adjustment',r.id,null,r);return json(res,201,r)}
if(p==='/api/periods'&&method==='GET'){await requirePerm(req,'periods.manage');return json(res,200,await q('SELECT * FROM periods ORDER BY year DESC,month DESC'))}
if(p.match(/^\/api\/periods\/\d+\/close$/)&&method==='POST'){const user=await requirePerm(req,'periods.manage'),id=Number(p.split('/')[3]),r=await one("UPDATE periods SET status='مغلقة',closed_at=NOW(),closed_by=$1 WHERE id=$2 AND status='مفتوحة' RETURNING *",[user.id,id]);if(!r)throw Error('الفترة غير موجودة أو مغلقة');await audit(user.id,'CLOSE','period',id,null,r,'إقفال الفترة');return json(res,200,r)}
if(p==='/api/settings'&&method==='GET'){await requirePerm(req,'settings.manage');const s=await q('SELECT key,value FROM settings');return json(res,200,Object.fromEntries(s.map(x=>[x.key,x.value])))}
if(p==='/api/settings'&&method==='PUT'){const user=await requirePerm(req,'settings.manage'),b=await body(req),before=Object.fromEntries((await q('SELECT key,value FROM settings')).map(x=>[x.key,x.value]));for(const [k,v] of Object.entries(b))await exec('INSERT INTO settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value',[k,String(v)]);const after=Object.fromEntries((await q('SELECT key,value FROM settings')).map(x=>[x.key,x.value]));await audit(user.id,'UPDATE','settings','global',before,after);return json(res,200,after)}
if(p==='/api/users'&&method==='GET'){await requirePerm(req,'users.manage');return json(res,200,await q('SELECT id,username,name,role,active,created_at FROM users ORDER BY id'))}
if(p==='/api/users'&&method==='POST'){const user=await requirePerm(req,'users.manage'),b=await body(req);if(!b.password||b.password.length<8)throw Error('كلمة المرور يجب أن تكون 8 أحرف على الأقل');const r=await one('INSERT INTO users(username,name,role,password_hash) VALUES($1,$2,$3,$4) RETURNING id,username,name,role,active,created_at',[b.username,b.name,b.role||'مدخل بيانات',hashPassword(b.password)]);await audit(user.id,'CREATE','user',r.id,null,r);return json(res,201,r)}
if(p.match(/^\/api\/users\/\d+$/)&&method==='PATCH'){const user=await requirePerm(req,'users.manage'),id=Number(p.split('/').pop()),b=await body(req),before=await one('SELECT id,username,name,role,active FROM users WHERE id=$1',[id]);if(!before)throw Error('المستخدم غير موجود');if(id===user.id&&b.active===false)throw Error('لا يمكنك تعطيل حسابك الحالي');const r=await one('UPDATE users SET name=COALESCE($1,name),role=COALESCE($2,role),active=COALESCE($3,active),password_hash=COALESCE($4,password_hash) WHERE id=$5 RETURNING id,username,name,role,active,created_at',[b.name??null,b.role??null,b.active==null?null:Boolean(b.active),b.password?hashPassword(b.password):null,id]);await audit(user.id,'UPDATE','user',id,before,r);return json(res,200,r)}
if(p==='/api/roles'&&method==='GET'){await requirePerm(req,'permissions.manage');return json(res,200,await Promise.all((await q('SELECT id,name FROM roles ORDER BY id')).map(async r=>({...r,permissions:await q('SELECT p.code,p.name FROM role_permissions rp JOIN permissions p ON p.id=rp.permission_id WHERE rp.role_id=$1',[r.id])})) ))}
if(p==='/api/permissions'&&method==='GET'){await requirePerm(req,'permissions.manage');return json(res,200,permissions.map(([code,name])=>({code,name})))}
if(p.match(/^\/api\/roles\/\d+\/permissions$/)&&method==='PUT'){const user=await requirePerm(req,'permissions.manage'),id=Number(p.split('/')[3]),b=await body(req),role=await one('SELECT * FROM roles WHERE id=$1',[id]);if(!role)throw Error('الدور غير موجود');const before=await q('SELECT p.code FROM role_permissions rp JOIN permissions p ON p.id=rp.permission_id WHERE rp.role_id=$1',[id]);const client=await pool.connect();try{await client.query('BEGIN');await client.query('DELETE FROM role_permissions WHERE role_id=$1',[id]);for(const code of b.codes||[]){const pp=await client.query('SELECT id FROM permissions WHERE code=$1',[code]);if(pp.rows[0])await client.query('INSERT INTO role_permissions(role_id,permission_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[id,pp.rows[0].id])}await client.query('COMMIT')}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}const after=await q('SELECT p.code FROM role_permissions rp JOIN permissions p ON p.id=rp.permission_id WHERE rp.role_id=$1',[id]);await audit(user.id,'UPDATE','role_permissions',id,before,after);return json(res,200,{role,permissions:after})}
if(p==='/api/audit'&&method==='GET'){await requirePerm(req,'audit.view');return json(res,200,await q('SELECT a.*,u.name user_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.id DESC LIMIT 1000'))}
if(p==='/api/backup'&&method==='POST'){const user=await requirePerm(req,'backup.manage');const tables=['users','roles','permissions','role_permissions','employees','employee_history','periods','opening_balances','ledger','attendance','production_items','production_logs','production_invoices','daily_allowances','withdrawals','adjustments','settings','audit_logs','jobs','attachments'];const snapshot={version:'4.0.0',created_at:now(),tables:{}};for(const t of tables){const rows=await q(`SELECT * FROM ${t}`);snapshot.tables[t]=rows.map(r=>{if(t==='attachments'&&r.data)r.data=Buffer.from(r.data).toString('base64');return r})}const name=`accounting-backup-${Date.now()}.json`;await exec('INSERT INTO backup_records(name,data,created_by) VALUES($1,$2,$3) ON CONFLICT(name) DO NOTHING',[name,snapshot,user.id]).catch(async e=>{if(e.code==='42P01'){await exec('CREATE TABLE IF NOT EXISTS backup_records(id BIGSERIAL PRIMARY KEY,name TEXT UNIQUE NOT NULL,data JSONB NOT NULL,created_by BIGINT,created_at TIMESTAMPTZ DEFAULT NOW())');await exec('INSERT INTO backup_records(name,data,created_by) VALUES($1,$2,$3)',[name,snapshot,user.id])}else throw e});await audit(user.id,'BACKUP','database',name,null,{name});return json(res,201,{name,path:`/api/backups/${encodeURIComponent(name)}`})}
if(p==='/api/backups'&&method==='GET'){await requirePerm(req,'backup.manage');await exec('CREATE TABLE IF NOT EXISTS backup_records(id BIGSERIAL PRIMARY KEY,name TEXT UNIQUE NOT NULL,data JSONB NOT NULL,created_by BIGINT,created_at TIMESTAMPTZ DEFAULT NOW())');return json(res,200,await q('SELECT name,pg_column_size(data) size,created_at FROM backup_records ORDER BY created_at DESC'))}
if(p.match(/^\/api\/backups\//)&&method==='GET'){await requirePerm(req,'backup.manage');await exec('CREATE TABLE IF NOT EXISTS backup_records(id BIGSERIAL PRIMARY KEY,name TEXT UNIQUE NOT NULL,data JSONB NOT NULL,created_by BIGINT,created_at TIMESTAMPTZ DEFAULT NOW())');const name=decodeURIComponent(p.split('/').pop()),b=await one('SELECT data FROM backup_records WHERE name=$1',[name]);if(!b)throw Error('النسخة غير موجودة');const buf=Buffer.from(JSON.stringify(b.data));res.writeHead(200,{'Content-Type':'application/json','Content-Disposition':`attachment; filename="${name}"`,'Content-Length':buf.length});return res.end(buf)}
if(p==='/api/restore'&&method==='POST'){const user=await requirePerm(req,'backup.manage'),b=await body(req);await exec('CREATE TABLE IF NOT EXISTS backup_records(id BIGSERIAL PRIMARY KEY,name TEXT UNIQUE NOT NULL,data JSONB NOT NULL,created_by BIGINT,created_at TIMESTAMPTZ DEFAULT NOW())');const snap=(await one('SELECT data FROM backup_records WHERE name=$1',[b.name]))?.data;if(!snap)throw Error('النسخة غير موجودة');const client=await pool.connect();try{await client.query('BEGIN');const tables=Object.keys(snap.tables||{}).reverse();for(const t of tables)await client.query(`TRUNCATE TABLE ${t} RESTART IDENTITY CASCADE`);for(const t of Object.keys(snap.tables||{})){for(const row of snap.tables[t]){if(t==='attachments'&&row.data)row.data=Buffer.from(row.data,'base64');const keys=Object.keys(row),vals=keys.map((_,i)=>`$${i+1}`);await client.query(`INSERT INTO ${t}(${keys.map(k=>'"'+k+'"').join(',')}) VALUES(${vals.join(',')})`,keys.map(k=>row[k]))}}for(const t of Object.keys(snap.tables||{})){if(['users','roles','permissions','employees','periods','ledger','attendance','production_items','production_logs','production_invoices','daily_allowances','withdrawals','adjustments','audit_logs','jobs','attachments','backup_records'].includes(t)){try{await client.query(`SELECT setval(pg_get_serial_sequence($1,'id'),COALESCE((SELECT MAX(id) FROM ${t}),1),true)`,[t])}catch{}}}await client.query('COMMIT')}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}await audit(user.id,'RESTORE','database',b.name,null,{restored_from:b.name},b.reason||'استعادة نسخة');return json(res,200,{ok:true,message:'تمت استعادة النسخة بنجاح'})}
if(p==='/api/attachments'&&method==='POST'){const user=await requirePerm(req,'attachments.manage'),b=await body(req);if(!b.entity_type||!Number.isInteger(Number(b.entity_id))||!b.file_name||!b.data_base64)throw Error('بيانات المرفق ناقصة');const raw=String(b.data_base64).replace(/^data:[^;]+;base64,/,'');const buf=Buffer.from(raw,'base64');if(buf.length>10*1024*1024)throw Error('حجم المرفق يتجاوز 10MB');const sha=crypto.createHash('sha256').update(buf).digest('hex');const r=await one('INSERT INTO attachments(entity_type,entity_id,file_name,mime_type,size_bytes,data,sha256,uploaded_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id,file_name,mime_type,size_bytes,sha256,created_at',[b.entity_type,Number(b.entity_id),b.file_name,b.mime_type||'application/octet-stream',buf.length,buf,sha,user.id]);await audit(user.id,'UPLOAD','attachment',r.id,null,r);return json(res,201,r)}
if(p.match(/^\/api\/attachments\/\d+\/download$/)&&method==='GET'){await requirePerm(req,'attachments.manage');const id=Number(p.split('/')[3]),a=await one('SELECT file_name,mime_type,data FROM attachments WHERE id=$1',[id]);if(!a)throw Error('المرفق غير موجود');const buf=Buffer.from(a.data);res.writeHead(200,{'Content-Type':a.mime_type||'application/octet-stream','Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(a.file_name)}`,'Content-Length':buf.length});return res.end(buf)}
if(p==='/api/reports/export'&&method==='GET'){await requirePerm(req,'reports.export');const type=u.searchParams.get('type')||'employees';const map={employees:'SELECT * FROM employees',attendance:'SELECT a.*,e.name employee_name FROM attendance a JOIN employees e ON e.id=a.employee_id',production:'SELECT p.*,e.name employee_name FROM production_logs p JOIN employees e ON e.id=p.employee_id',withdrawals:'SELECT w.*,e.name employee_name FROM withdrawals w JOIN employees e ON e.id=w.employee_id',ledger:'SELECT l.*,e.name employee_name FROM ledger l JOIN employees e ON e.id=l.employee_id'};const rows=await q(map[type]||map.employees);const out=csv(rows);res.writeHead(200,{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename="${type}.csv"`});return res.end(out)}
if(p==='/api/report/print'&&method==='GET'){await requirePerm(req,'reports.view');const type=u.searchParams.get('type')||'employees';const rows=await q(type==='ledger'?'SELECT l.*,e.name employee_name FROM ledger l JOIN employees e ON e.id=l.employee_id ORDER BY l.id DESC':type==='production'?'SELECT p.*,e.name employee_name FROM production_logs p JOIN employees e ON e.id=p.employee_id ORDER BY p.id DESC':'SELECT * FROM employees');const cols=rows.length?Object.keys(rows[0]):[];return sendHtml(res,htmlReport('تقرير '+type,`<table><thead><tr>${cols.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${r[c]??''}</td>`).join('')}</tr>`).join('')}</tbody></table>`))}
if(method==='GET'){let file=p==='/'?path.join(publicDir,'index.html'):path.join(publicDir,p);if(!fs.existsSync(file)||fs.statSync(file).isDirectory())file=path.join(publicDir,'index.html');const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8'};res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'text/plain; charset=utf-8'});return fs.createReadStream(file).pipe(res)}return json(res,404,{error:'Not found'});
}catch(e){console.error(e);return json(res,e.status||400,{error:e.message||'حدث خطأ'})}}
init().then(async()=>{try{await catchUpDaily()}catch(e){console.error('Initial daily payroll catch-up failed:',e.message)}scheduleDaily();http.createServer(handler).listen(PORT,()=>console.log(`Accounting System 4.0 running on port ${PORT}`));}).catch(e=>{console.error('Database initialization failed:',e);process.exit(1)});
